apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{env}}-{{domain}}-{{name}}-tls
spec:
  secretName: {{host}}-tls
  issuerRef:
    name: letsencrypt-{{env}}
    kind: ClusterIssuer
  commonName: {{host}}
  dnsNames:
  - {{host}}
  acme:
    config:
    - http01:
        ingress: {{name}}
      domains:
      - {{host}}