apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{name}}-tls
  namespace: {{namespace}}
spec:
  secretName: {{name}}-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: {{domain}}
  dnsNames:
  - {{domain}}
  acme:
    config:
    - http01:
        ingress: fanout-ingress
      domains:
      - {{domain}}