apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{name}}
spec:
  secretName: {{name}}
  issuerRef:
    name: letsencrypt-{{env}}
    kind: ClusterIssuer
  commonName: {{host}}
  dnsNames:
  - {{host}}
  acme:
    config:
    - http01:
        ingress: {{name}}
      domains:
      - {{host}}