apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
  namespace: {{namespace|default(default)}}
spec:
  replicas: {{replicas|default(1)}}
  strategy:
      rollingUpdate:
          maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - name: {{name}}
        image: "{{image}}:{{tag|default(latest)}}"
        ports:
        - containerPort: {{port|default(80)}}