apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: {{replicas|default(1)}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - name: {{name}}
        image: {{image}}
        ports:
        - containerPort: {{port|default(80)}}