apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{name}}
          servicePort: {{port|default(80)}}