apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
  annotations:
      kubernetes.io/ingress.global-static-ip-name: {{name}}-ingress
      certmanager.k8s.io/cluster-issuer: letsencrypt-{{env|default(staging)}}
  labels:
    app: {{name}}
spec:
  tls:
  - secretName: {{env|default(staging)}}-tls
    hosts:
    - {{name}}.{{domain}}
  backend:
      serviceName: {{name}}
      servicePort: {{name}}-port