apiVersion: extesions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
  namespace: {{namespace|default(default)}}
  annotations:
      kubernetes.io/ingress.global-static-ip-name: {{name}}-ingress
      certmanager.k8s.io/cluster-issuer: letsencrypt-{{env}}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{name}}
          servicePort: {{port|default(80)}}
    tls:
    - secretName: {{name}}-tls
      hosts:
      - {{domain}}