apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
  annotations:
      kubernetes.io/ingress.global-static-ip-name: {{name}}-{{env}}-ingress
      certmanager.k8s.io/cluster-issuer: letsencrypt-{{env}}
  labels:
    app: {{name}}
spec:
  tls:
  - secretName: {{name}}
    hosts:
    - {{host}}
  backend:
      serviceName: {{name}}
      servicePort: 8080