apiVersion: v1
kind: Service
metadata:
  name: {{name}}-{{env}}
  labels:
    app: {{name}}-{{env}}
spec:
  type: NodePort
  selector:
    app: {{name}}
  ports:
  - port: {{port|default(8080)}}
    targetPort: {{target_port|default(8080)}}
    protocol: TCP
    name: {{name}}-port
