apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
spec:
  type: NodePort
  ports:
  - port: {{port|default(80)}}
    targetPort: {{port|default(80)}}
    protocol: TCP
    name: http
  selector:
    app: {{name}}