apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kdeployer-tls
  namespace: default
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kdeployer.utviklr.no
  dnsNames:
  - kdeployer.utviklr.no
  acme:
    config:
    - http01:
        ingress: kdeployer
      domains:
      - kdeployer.utviklr.no